### ISSUE TITLE
ModuleNotFoundError: No module named 'sentence_transformers'

### ISSUE THREAD

**Issue by Zildj1an** [jlonge4/local_llama#8]
Using macOS Monterrey (v12.6), I run:

```
$ python -m streamlit run local_llama.py
```

and get the error:

```
ModuleNotFoundError: No module named 'sentence_transformers'
```

I have a fix and plan to pull request

**Comment by jlonge4** [comment]
@Zildj1an thanks for providing a fix with the issue! Awesome, I have merged your changes 👍🏼👍🏼
